# Generated by Django 5.0.2 on 2024-03-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='order', to='customer.menuitem'),
        ),
    ]
